server {
    listen 80;
    listen [::]:80;

    server_name 31.77.206.19;
    root /var/www/le-monde-miniapp;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
